# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: 
      name: "{{ packages }}" 
      state: present
    vars:
      packages:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Add an apt key for mongodb repo
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927
      state: present

  - name: Add mongodb repository
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
      filename: mongodb-org-3.2.list

  - name: Install mongodb
    apt:
      name: mongodb-org
      state: present
      update_cache: yes
 
  - name: Start and enable mongodb service
    service:
      name: mongod
      state: started
      enabled: yes

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no

  tasks:
  - name: Remove me after adding real things
    debug:
      msg: "В этом сценарии нужно добавить модули для деплоя приложения, после можно удалить вызов модуля debug, который выводит это сообщение"
